spin_version = "1"
authors = ["wmcgee3"]
description = ""
name = "spin-multi-route"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "root"
source = "target/wasm32-wasi/release/root.wasm"
[component.trigger]
route = "/"
[component.build]
command = "cargo build --target wasm32-wasi --release"

[[component]]
id = "hello"
source = "target/wasm32-wasi/release/hello.wasm"
[component.trigger]
route = "/hello"
[component.build]
command = "cargo build --target wasm32-wasi --release"

[[component]]
id = "thing"
source = "target/wasm32-wasi/release/thing.wasm"
[component.trigger]
route = "/things/..."
[component.build]
command = "cargo build --target wasm32-wasi --release"

[[component]]
id = "things"
source = "target/wasm32-wasi/release/things.wasm"
[component.trigger]
route = "/things"
[component.build]
command = "cargo build --target wasm32-wasi --release"
